import "../Style/projects.sass";
import { Card } from "./ProjectCards";

interface Project {
  imgPath: string;
  githubURL: string;
  demoURL: string;
  name: string;
  description: string;
}

const Project = () => {
  const projects: Project[] = [
    {
      imgPath: "./images/currency_globe.jpg",
      githubURL: "https://github.com/bishalkar10/Currency-Globe",
      demoURL: "https://peppy-creponne-8ffb54.netlify.app/",
      name: "Currency Globe",
      description:
        "A web appliation to get the coversion rate of different currencies all over the world, show the past 7 days exchange rate in chart format and live exchange rates of many currencies. This web app also support multiple theme colors. Utilizing Javascript, Tailwind CSS, ReactJS, Redux Toolkit, React-Router-Dom, Axios etc.",
    },
    {
      name: "Image Gallery",
      imgPath: "./images/image_gallery.png",
      githubURL: "https://github.com/bishalkar10/Image-Gallery",
      demoURL: "https://bishalkar10.github.io/Image-Gallery/",
      description:
        "This is one of my Vanilla Javascript project. I have used Pexels database to fetch images. User can search for images and they will get images related to their search. I have used HTML, Javascript, Tailwindcss to build this app. This app is mobile responsive and features infinite scroll. ",
    },
    {
      name: "Movie App",
      imgPath: "./images/movie_app.jpg",
      githubURL: "https://github.com/bishalkar10/Movies-App",
      demoURL: "https://lively-flan-375b2d.netlify.app/",
      description:
        "This is a web application built using HTML, Tailwind CSS, Javascript, React.js. I have used Axios library to fetch movie data from themoviesdb database. User can search for movies and they will get details of movies. This app is mobile responsive. This app utilzes ContextAPI to manage state. This app has multiple routes and features infinite scroll in two pages.",
    },
    // {
    // 	name: "Blog Generator",
    // 	imgPath: "./images/blog_generator.jpg",
    // 	githubURL: "https://github.com/bishalkar10/Blog-Generator",
    // 	demoURL: "https://elaborate-buttercream-cf0624.netlify.app/",
    // 	description:
    // 		"This is a responsive web application built using HTML5, Tailwindcss, Javascript, React.js, React-router-dom and powered by openAI API. User can click on the generate button and they will get a blog generated by AI. This app has two routes.",
    // },

    {
      imgPath: "./images/portfolio_website.jpg",
      githubURL: "https://github.com/bishalkar10/Portfolio-Website",
      demoURL: "https://gain-prasad-kar.netlify.app/",
      name: "Portfolio Website",
      description:
        "This is my personal portfolio website you are looking at. I have used HTML5, Sass, React.js, Typescript, to build this. I have made it mobile responsive so you can see it in any size of screen.",
    },
    {
      imgPath: "./images/Weather App 350x197.png",
      githubURL: "https://github.com/bishalkar10/Weather-App",
      demoURL: "https://bishalkar10.github.io/Weather-App/",
      name: "Weather App",
      description:
        "This is a weather web application built using html, tailwindcss, javascript. I have used 'OpenWeatherMap' API to fetch weather data. User can enter their city name and they will get details of sky condition and weather temperature.",
    },
  ];
  return (
    <section id="projects">
      <h2 className="title">Projects</h2>
      <div className="project-container">
        {projects.map((project, index) => {
          return (
            <Card
              index={index}
              key={index}
              imgPath={project.imgPath}
              githubURL={project.githubURL}
              demoURL={project.demoURL}
              name={project.name}
              description={project.description}
            />
          );
        })}
      </div>
    </section>
  );
};

export default Project;
